algoritmo "os 4 numeros"
// Função :calcular o quadrados dos numeros abaixo
// Autor :Gustavo Ap.
// Data : 11/03/2020
// Seção de Declarações 
var
n1: real
n2: real
n3: real
n4: real
result: real
inicio
// Seção de Comandos
//entrada
escreval ("digite o primeiro numero")
leia(n1)
escreval ("digite o segundo numero")
leia(n2)
escreval ("digite o terceiro numero")
leia(n3)
escreval ("digite o quarto numero")
leia(n4)
//processamento
result <- (n1^2+n2^2+n3^2+n4^2)
//saida
escreval ("o resultado sera" , result)
fimalgoritmo
