algoritmo "calcular o preço do carro com impostos"
// Função :calcular o preço do carro com impostos
// Autor :Gustavo Ap.
// Data : 11/03/2020
// Seção de Declarações 
var
valor: real
result: real
inicio
// Seção de Comandos
//entrada
escreval ("digite o valor do carro")
leia(valor)
//processamento
result <-valor*1.45*1.28
//saida
escreval ("O valor do carro com imposto e" , result)
fimalgoritmo
