algoritmo "velocidade media"
// Função :calcula a velocidade media de um carro e tambem calcula a multa
// Autor :Gustavo Ap.
// Data : 20/05/2020
// Seção de Declarações 
var
percurso: real
tempo: real
result: real
inicio
// Seção de Comandos
escreval("qual foi o percurso percorrido")
leia (percurso)
escreval("qual foi o tempo gasto nesse percurso")
leia (tempo)
//processamento
result<- (percurso/tempo)
//saida
escreval ("voce percorreu:" ,result)
fimalgoritmo
