algoritmo "Cotaçao do dolar"
// Função :calcular quanto dinheiro em dolar o usuario tem
// Autor :Gustavo
// Data : 11/03/2020
// Seção de Declarações 
var
dolar: real
valor: real
result: real
inicio
//entrada
escreval ("digite quanto o dolar esta hj")
leia(dolar)
escreval ("digite quanto voce tem")
leia(valor)
//processamento
result <- valor/dolar
//saida
escreval ("voce tem $" , result)
// Seção de Comandos 
fimalgoritmo
